version: "3.3"
services:
  semesterstats:
    image: semesterstat:1.0.6
    build: .
    ports:
      - "9000:9000"
    volumes:
      - "./imported:/app/imported"
    stop_signal: SIGINT
    tty: true
    restart: unless-stopped
