theme:
  name: material
  palette:
    scheme: slate
    accent: blue
    primary: red

site_name: Semester-Stats
repo_url: https://github.com/Rushyanth111/Semester-Stats
repo_name: Semester-Stats
site_author: Rushyanth S

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

nav:
  - Home: "index.md"
  - Calculation: "Calculations.md"
  - Database Structure: "Database.md"
  - CSV Format: "CsvFormat.md"
  - API V1:
      - Home: "v1/api.md"
      - Department: "v1/dept.md"
      - Student: "v1/student.md"
      - Subject: "v1/subject.md"
      - Batch: "v1/batch.md"
  - API v2:
      - Home: "v2/home.md"
      - Batch: "v2/batch.md"
      - Student: "v2/student.md"
      - Deptartment: "v2/dept.md"
      - Subject: "v2/subject.md"
      - Document: "v2/document.md"
      - Summary: "v2/summary.md"
      - info: "v2/info.md"
