[tool.poetry]
name = "semester-stats"
version = "0.1.0"
description = "A tool to calculate the semester statistics"
authors = ["Rushyanth111 <42034084+Rushyanth111@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.6"
peewee = "^3.13.3"
docx-mailmerge = "^0.5.0"

[tool.poetry.dev-dependencies]
pep8-naming = "^0.10.0"
flake8 = "^3.8.1"
black = {version = "^19.10b0", allow-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
