DepartmentCodeDictionary: dict = {
    "AE": "Aeronautical Engineering",
    "MAE": "Aeronautical Engineering",
    "AT": "Architecture",
    "AU": "Automobile Engineering",
    "MAU": "Automotive Engineering",
    "BT": "Bio-technology",
    "BM": "Biomedical Engineering",
    "LBI": "Biomedical Signal Processing and Instrumentation",
    "CC": "Ceramics and Cement Technology",
    "HCE": "Chemical Engineering",
    "CH": "Chemical Engineering",
    "CV": "Civil Engineering",
    "LCS": "Communication Systems",
    "MCS": "Computational Analysis in Mechanical Sciences",
    "CCS": "Computer Aided Design of Structures",
    "ECD": "Computer Applications in Industrial Drives",
    "SCE": "Computer Engineering",
    "MCM": "Computer Integrated Manufacturing",
    "SCN": "Computer Network Engineering",
    "SCS": "Computer Science and Engineering",
    "CS": "Computer Science and Engineering",
    "CCT": "Construction Technology",
    "CT": "Construction Technology and Management",
    "MDE": "Design Engineering",
    "LDN": "Digital Communications and Networking",
    "LDC": "Digital Communications Engineering",
    "LDE": "Digital Electronics",
    "LDS": "Digital Electronics and Communcation Systems",
    "EE": "Electrical and Electronics Engineering",
    "LEL": "Electronics",
    "EC": "Electronics and Comm Engineering",
    "MEA": "Engineering Analysis and Design",
    "CEE": "Environmental Engineering",
    "EV": "Environmental Engineering",
    "CHT": "Highway Technology",
    "IP": "Industrial and Production Engineering",
    "MAR": "Industrial Automation and Robotics",
    "LIE": "Industrial Electronics",
    "IM": "Industrial Engineering and Management",
    "IS": "Information Science and Engineering",
    "SIT": "Information Technology",
    "IT": "Instrumentation Technology",
    "MMD": "Machine Design",
    "MS": "Manufacturing Science and Engineering",
    "MBA": "Master of Business Administration",
    "MCA": "Master of Computer Applications",
    "MEM": "Master of Engineering Management",
    "ME": "Mechanical Engineering",
    "ML": "Medical Electronics",
    "EMS": "Microelectronics and Control Systems",
    "MI": "Mining Engineering",
    "LNI": "Networking and Internet Engineering",
    "PM": "Polymer Science and Technology",
    "EPE": "Power Electronics",
    "EPS": "Power Systems Engineering",
    "MPD": "Product Design and Manufacturing",
    "MSE": "Production Engineering",
    "MPT": "Production Engineering and System Technology",
    "LSP": "Signal Processing",
    "ST": "Silk Technology",
    "SSE": "Software Engineering",
    "CSE": "Structural Engineering",
    "TE": "Telecommunication Engineering",
    "JTT": "Textile Technology",
    "TX": "Textile Technology",
    "MTP": "Thermal Power Engineering",
    "MTE": "Tool Engineering",
    "CTM": "Transportation Engineering and Management",
    "LVS": "VLSI Design and Embedded Systems",
    "BS": "Basic Science",
    "XTR": "Extra Subject/Optional",
}
